name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: |
          curl -L -o ninja-linux.zip https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip
          unzip ninja-linux.zip -d bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Configure
        run: cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build